spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///zzydemo1?serverTimezone=UTC
    username: root
    password: root
    druid:
      # 初始化连接数
      initial-size: 10
      # 最大连接数
      max-active: 60
      # 可以使用这个sql语句检查数据库连接
      validation-query: select 1 from dual

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.zzy
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 自定义配置项
img:
  dir: e:/upload/et2209
  prefix: /files

pagehelper:
  # 分页合理化参数，默认值为false;
  # 当该参数设置为 true 时，pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页。
  reasonable: true
